main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: 3.2.8.2
description: The ultimate moderation plugin!
author: Shortninja,Qball
softdepend: [PacketListenerApi]
api-version: 1.13
