main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: 3.3.1.0
description: The ultimate moderation plugin!
author: Shortninja,Qball
softdepend: [PacketListenerApi]
api-version: 1.13
