main: net.shortninja.staffplus.StaffPlus
name: StaffPlus
version: 3.3.2.1
description: The ultimate moderation plugin!
author: Shortninja,Qball
softdepend: [PacketListenerApi, PlaceholderAPI]
api-version: 1.13
